version: "3.0"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ShoppingTesting
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    restart: always
    ports:
      - 3306:3306

  shopping-testing:
    depends_on:
      - db
    image: metinirden/shopping-testing:runtime
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
